name: design
type: directory
description: >
  Authoritative design parameter definitions for Megadroid, including joints,
  geometry, and other machine-readable constraints. Files in this directory
  serve as the single source of truth for system configuration.
authority: authoritative