name: tools
type: directory
description: >
  Validation, consistency-checking, and rehydration scripts that enforce design
  constraints and keep derived documents synchronized with authoritative sources.
authority: tooling