name: firmware
type: directory
description: >
  Embedded firmware for real-time motor, joint, and low-level hardware control,
  intended to run on RP2350-CAN boards or equivalent MCUs.
authority: implementation